version: '3.5'

services:
  cache:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    restart: unless-stopped

  postgres:
    image: postgres:13.5
    restart: unless-stopped
    environment:
      - POSTGRES_USER=heal
      - POSTGRES_PASSWORD=ishuman321
    volumes:
      - postgres-nest-backend-nx:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    restart: unless-stopped
    ports:
      - '9092:9092'
    environment:
      CLUSTER_ID: 4L6g3nShT-eMCtK--X86sw
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_EXTERNAL_HOSTNAME}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      KAFKA_DELETE_TOPIC_ENABLE: true
      KAFKA_METADATA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_METADATA_MAX_RETENTION_MS: 604800000
      KAFKA_LOG4J_LOGGERS: 'org.apache.kafka.image.loader.MetadataLoader=WARN'
    volumes:
      - kafka-data:/var/lib/kafka

volumes:
  postgres-nest-backend-nx:
  kafka-data:
  redis-data:
